name: manage-azure-policy-03e98a28
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policy/policies/Deploy_Threat_Detection_on_SQL_servers_36d49e87-48c4-4f2e-beed-ba4ed02b71f5/**'
#      - .github/workflows/manage-azure-policy-03e98a28.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_03e98a28}}
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policy/policies/Deploy_Threat_Detection_on_SQL_servers_36d49e87-48c4-4f2e-beed-ba4ed02b71f5/**
